version: '3.7'

services:
  hania.netcore.mongo.sample:
    image: hanianetcoremongosample:dev
    container_name: Hania.NetCore.Mongo.Sample
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Hania.NetCore.Mongo.Sample"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_hania.netcore.mongo.sample$
    volumes:
      - C:\Users\akbar\source\repos\Hania.NetCore.Mongo.Sample\Hania.NetCore.Mongo.Sample:/app
      - C:\Users\akbar\source\repos\Hania.NetCore.Mongo.Sample:/src
      - C:\Users\akbar\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_hania.netcore.mongo.sample$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_hania.netcore.mongo.sample$ \"/app/bin/Debug/netcoreapp3.1/Hania.NetCore.Mongo.Sample.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true